### Data Set up ###
#### Preamble ####
# Purpose: Fix manual entry errors from Qualtric submissions. These were records with issues such as 
# spelling errors, incorrect name order, students with alternative first names, etc. This 

# Author: Jaffa Romain
# Contact: jaffa.romain@mail.utoronto.ca

## First set of fixes
groups[groups == "brian -"] <- "brian do"
groups[groups == "accidentallyenteredtoomanyteammembers woops"] <- NA
groups[groups == "sara"] <- "sara al-marashdeh"
groups[groups == "TiffanyYuChing Lam"] <- "Tiffany Lam"
groups[groups == "LarsStadil Trier"] <- "Lars Trier"
groups[groups == "LauralLee CasimiriBenben"] <- "Laurel-Lee Casimiri-Benben"
groups[groups == "Saad S"] <- "Saad Siddiqui"
groups[groups == "Saad Siddiqqi"] <- "Saad Siddiqui"
groups[groups == "Rachel Sw"] <- "Rachel Swampillai"
groups[groups == "Kia G"] <- "Kia Gharibi"
groups[groups == "santhiyaa jeyamohan"] <- "santhiyaa jeyamohan"
groups[groups == "Laisha Sebastiampillai"] <- "Laisha Sebastian"
groups[groups == "Laisha"] <- "Laisha Sebastian"
groups[groups == "Fabiha"] <- "Fabiha Chowdhury"
groups[groups == "anshika"] <- "Anshika Narang"
groups[groups == "dorin"] <- "Dorian Russell"
groups[groups == "Thiviya Muthucumarasamy"] <- "Thiviya Muthugumarasamy"
groups[groups == "Bridy Krishnarajah"] <- "Bridy Krishnaraja"
groups[groups == "Arifa Chowdhury"] <- "Arifa Chowdhury"
groups[groups == "Yang Allysha"] <- "Allysha Yung"
groups[groups == "Carmen"] <- "Carmen Radoescu"
groups[groups == "Glenys  Tanesia"] <- "Glenys Tanesia"
groups[groups == "Glenys"] <- "Glenys Tanesia"
groups[groups == "Ivan Manusev"] <- "Ivan Manasuev"
groups[groups == "JasmineDeborah Shum"] <- "Jasmine Shum"
groups[groups == "AbbasTariq Khan"] <- "Abbas Tariq Khan"
groups[groups == "Abbas TariqKhan"] <- "Abbas Tariq Khan"
groups[groups == "Abbas Khan"] <- "Abbas Tariq Khan"
groups[groups == "OmerIftikhar Ahmed"] <- "Omer Iftikhar  Ahmed"
groups[groups == "Omer Iftikhar"] <- "Omer Iftikhar  Ahmed"
groups[groups == "Omer Iftekhar"] <- "Omer Iftikhar  Ahmed"
groups[groups == "juan -"] <- "Juan Guibert"
groups[groups == "Rania Asaad"] <- "Rania Assaad"
groups[groups == "Japdeep"] <- "Japdeep Gill"
groups[groups == "Tomas"] <- "Tomas quattrochi"
groups[groups == "vir(myself) Samra"] <- "Manvir Samra"
groups[groups == "Dakshin Soorya"] <- "Dakshin Sooryamoorthy"
groups[groups == "ChristopherKwanHo(thatsme) Luey"] <- "Christopher Luey"
groups[groups == "ChristopherKwanHo Luey"] <- "Christopher Luey"
groups[groups == "christopherkwanho luey"] <- "Christopher Luey"
groups[groups == "KwanHo Luey"] <- "Christopher Luey"
groups[groups == "Renzon Reyes"] <- "Renzo Reyes"
groups[groups == "Yili(Tina) Jiang"] <- "yili jiang"
groups[groups == "Tina Jiang"] <- "Yili Jiang"
groups[groups == "ike udonsi"] <- "IKECHUKWU UDONSI"
groups[groups == "alex harold"] <- "Alexander Harold"
groups[groups == "an chen"] <- "Ann Chen"
groups[groups == "Manvir(myself) Samra"] <- "manvir samra"
groups[groups == "Japdeep"] <- "Japdeep Gill"
groups[groups == "Tomas"] <- "Tomas quattrochi"
groups[groups == "Lin Melania"] <- "Marina Lin"
groups[groups == "Calvin Vaughn"] <- "Calvin Vaughan"
groups[groups == "Tao(Anthony) Yin"] <- "Anthony Yin"
groups[groups == "Me Me"] <- "Rami Ashtar"
groups[groups == "Honey HS"] <- "Honey Soe"
write_csv(groups, "test.csv")

## Second set of fixes
groups[groups == "Chia Teo"] <- "ChiaYin Teo"
groups[groups == "Myself"] <- "Ozan Coskun"
groups[groups == "Ozan"] <- "Ozan Coskun"
groups[groups == "Heather"] <- "Heather Kelsall"
groups[groups == "Jordan"] <- "Jordan Lee"
groups[groups == "ChristinaEvelynSastro Wijoyo"] <- "ChristinaE.S. Wijoyo"
groups[groups == "Lee Benben"] <- "Laurel-Lee Casimiri-Benben"
groups[groups == "Shem Gunasekeran"] <- "Shem Gunasekaran"
groups[groups == "WingYuGloria Lo"] <- "Gloria Lo"
groups[groups == "omeriftikhar ahmed"] <-  "Omer Iftikhar  Ahmed"
groups[groups == "Glenys"] <- "Glenys Tanesia"
groups[groups == "Hu JunqI"] <- "Junqi Hu"
groups[groups == "Samantha Wang"] <- "samantha wong"
groups[groups == "Qianting"] <- "Qianting Yu"
groups[groups == "Omar Robbat"] <- "Omar Rabbat"
groups[groups == "Rob Kolaja"] <- "Robert Kolaja"
groups[groups == "james"] <- "James Macek"
groups[groups == "Lebiez Piranaj"] <- "Liebiez Piranaj"
groups[groups == "LEBEIZ"] <- "Liebiez Piranaj"
groups[groups == "BARAKAT"] <- "Bakarat Omotosho"
groups[groups == "Tao(Anthony) Yin"] <- "Anthony Yin"
groups[groups == "TeoChai Yin"] <- "Chia Teo"
groups[groups == "ChiaYin Teo"] <-  "Chia Teo"

groups[groups == "Heather"] <-  "Heather Kelsall"
groups[groups == "Jordan"] <-  "Jordan Lee"
groups[groups == "Elkebir"] <-  "Elkebir Lamrani"
groups[groups == "ravi"] <-  "Ravi Seegobin"
groups[groups == "jun"] <-  "Haijun Li"
groups[groups == "alan"] <-  "Xinqiang He"
groups[groups ==  "Xinqiang(Alan) He"] <-  "Xinqiang He"
groups[groups == "Qianting"] <-  "Qianting Yu"
groups[groups == "lily ling"] <-  "Lily Lin"
groups[groups == "Jun Jian"] <-  "junxian jian"
groups[groups == "GraceYC Liu"] <-  "Grace Liu"
groups[groups == "Amy Shen"] <-  "YiYun Shen(Amy)"
groups[groups == "Nam"] <-  "Nam Duong"
groups[groups == "FrancesMyla Dimagiba"] <-  "Myla Damigba"
groups[groups == "TszChingJessie Yu"] <-  "Jessie Yu"
groups[groups == "Cheng Chia"] <-  "ChiaAn Cheng"
groups[groups == "Li YuanYuan"] <-  "YuanYuan Li"
groups[groups == "Candace(Dahyun) Kim"] <-  "Candace Kim"
groups[groups == "EvonneJoseph"] <-  "Evonne Joseph"
groups[groups == "Haolong Fan(Felix)"] <-  "Haolong Fan"
groups[groups == "Lisa"] <-  "Lisa Derzhavina"
groups[groups == "Lisa D"] <- "Lisa Derzhavina"
groups[groups == "Tony HUi"] <-  "xuechao hui"
groups[groups == "Tony Hui"] <-   "xuechao hui"
groups[groups == "Nidusha Nithi"] <-  "Nidusha Nithiananthan"
groups[groups == "Nidusha Nithiananathan"] <-  "Nidusha Nithiananthan"
groups[groups == "Marina Ravi"] <-  "Marina Raji"
groups[groups == "Marina R"] <-  "Marina Raji"
groups[groups == "MohammadShaad Multani"] <-  "Shaad Multani"
groups[groups == "WEI LU"] <-  "WeiDe Lu"
groups[groups == "Didier Ramses"] <-  "Ramazani Didier"
groups[groups == "Kevin Shin"] <-  "Yongseung Shin"
groups[groups == "Paul Jin"] <-  "Shiyang Jin"

write_csv(groups, "test.csv")
groups[groups == ""] <-  ""
groups[groups == ""] <-  ""
groups[groups == ""] <-  ""
groups[groups == ""] <-  ""
groups[groups == ""] <-  ""
groups[groups == ""] <-  ""
groups[groups == ""] <-  ""
groups[groups == ""] <-  ""
groups[groups == ""] <-  ""
groups[groups == ""] <-  ""
groups[groups == ""] <-  ""









